export const recipes = [
  {
    id: 1,
    title: "Sushi Grade Poke Bowl",
    author: "Sarah Chen",
    authorInitials: "SC",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
    description: "Fresh salmon, edamame, avocado with sushi rice and sesame ginger dressing",
    healthScore: 95,
    calories: 520,
    prepTime: "15 min",
    likes: 2340,
    comments: 180,
    tags: ["High-Protein", "Gluten-Free", "Pescatarian"],
    verified: true,
    servings: 2,
    nutrition: { protein: 42, carbs: 58, fat: 18, fiber: 8 },
    ingredients: [
      { amount: "200g", name: "Fresh salmon fillet" },
      { amount: "1 cup", name: "Cooked sushi rice" },
      { amount: "½ cup", name: "Edamame" },
      { amount: "1", name: "Avocado, sliced" },
      { amount: "2 tbsp", name: "Sesame seeds" },
      { amount: "3 tbsp", name: "Ginger soy dressing" },
    ],
    steps: [
      { title: "Prep the rice", description: "Cook sushi rice and let cool slightly" },
      { title: "Cube the salmon", description: "Cut fresh salmon into bite-sized cubes" },
      { title: "Assemble bowl", description: "Layer rice, vegetables, and salmon" },
      { title: "Season and serve", description: "Drizzle dressing and sprinkle sesame seeds" },
    ],
  },
  {
    id: 2,
    title: "Green Smoothie Power Bowl",
    author: "Maya Patel",
    authorInitials: "MP",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    description: "Blended spinach, banana, berries with Greek yogurt and granola topping",
    healthScore: 88,
    calories: 310,
    prepTime: "5 min",
    likes: 1890,
    comments: 145,
    tags: ["Vegan", "Gluten-Free", "Quick Meal"],
    verified: true,
    servings: 1,
    nutrition: { protein: 18, carbs: 45, fat: 8, fiber: 6 },
    ingredients: [
      { amount: "2 cups", name: "Fresh spinach" },
      { amount: "1", name: "Ripe banana" },
      { amount: "½ cup", name: "Mixed berries" },
      { amount: "½ cup", name: "Greek yogurt" },
      { amount: "⅓ cup", name: "Granola" },
      { amount: "½ cup", name: "Almond milk" },
    ],
    steps: [
      { title: "Blend greens", description: "Blend spinach with almond milk until smooth" },
      { title: "Add fruits", description: "Add banana and berries, blend until creamy" },
      { title: "Pour and layer", description: "Pour into bowl and add yogurt" },
      { title: "Top with granola", description: "Add granola and fresh berries on top" },
    ],
  },
  {
    id: 3,
    title: "Grilled Chicken & Quinoa",
    author: "James Martinez",
    authorInitials: "JM",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
    description: "Herb-marinated chicken breast with quinoa and roasted vegetables",
    healthScore: 92,
    calories: 480,
    prepTime: "35 min",
    likes: 2100,
    comments: 210,
    tags: ["High-Protein", "Keto", "Low-Carb"],
    verified: true,
    servings: 2,
    nutrition: { protein: 45, carbs: 35, fat: 12, fiber: 7 },
    ingredients: [
      { amount: "2 x 180g", name: "Chicken breasts" },
      { amount: "1 cup", name: "Cooked quinoa" },
      { amount: "2 cups", name: "Mixed roasted vegetables" },
      { amount: "2 tbsp", name: "Olive oil" },
      { amount: "2 cloves", name: "Garlic, minced" },
      { amount: "1 tbsp", name: "Lemon juice" },
    ],
    steps: [
      { title: "Marinate chicken", description: "Mix olive oil, garlic, lemon and coat chicken" },
      { title: "Grill chicken", description: "Grill for 6-7 minutes each side until cooked" },
      { title: "Cook quinoa", description: "Boil quinoa for 15 minutes" },
      { title: "Roast vegetables", description: "Roast vegetables at 200°C for 20 minutes" },
    ],
  },
  {
    id: 4,
    title: "Mediterranean Mezze Plate",
    author: "Leila Abdel",
    authorInitials: "LA",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80",
    description: "Hummus, falafel, tabbouleh, grilled vegetables with pita bread",
    healthScore: 85,
    calories: 420,
    prepTime: "25 min",
    likes: 1650,
    comments: 120,
    tags: ["Vegan", "Gluten-Free", "High-Protein"],
    verified: true,
    servings: 2,
    nutrition: { protein: 16, carbs: 52, fat: 18, fiber: 10 },
    ingredients: [
      { amount: "1 cup", name: "Hummus" },
      { amount: "8 pieces", name: "Baked falafel" },
      { amount: "1 cup", name: "Tabbouleh" },
      { amount: "2 cups", name: "Grilled vegetables" },
      { amount: "2", name: "Whole wheat pita" },
      { amount: "½ cup", name: "Olives and feta" },
    ],
    steps: [
      { title: "Prepare hummus", description: "Mix chickpeas, tahini, lemon and garlic" },
      { title: "Bake falafel", description: "Bake falafel at 190°C for 20 minutes" },
      { title: "Make tabbouleh", description: "Combine parsley, tomato, bulgur and dressing" },
      { title: "Grill vegetables", description: "Grill eggplant, zucchini and peppers" },
    ],
  },
]
